language: node_js

node_js:
    - "9"
    - "8"

before_install:
    - pip install --user codecov

install:
    - npm install

script:
    - npm run lint 
    - node test.js

cache:
    directories:
        - "node_modules"

after_success:
    - codecov --file coverage/lcov.info --disable search
